name: Docker Image CI2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Esta l√≠nea permite ejecutar el workflow manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonando Repositorio
      uses: actions/checkout@v3

    - name: Log in to GitHub Docker registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/my-app:latest

    - name: Push the image to GitHub Packages
      run: docker push ghcr.io/${{ github.repository_owner }}/my-app:latest
